name: Rust - Release creation

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  create-release:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            x86_64-pc-windows-gnu,
            x86_64-unknown-linux-musl,
            x86_64-apple-darwin,
          ]

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXTRA_COMMAND_FLAGS: "--bin adb_cli"
          CARGO_TARGET_X86_64_APPLE_DARWIN_LINKER: /opt/osxcross/target/bin/o64-clang
        with:
          RUSTTARGET: ${{ matrix.target }}
          SRC_DIR: "adb_cli"
          TOOLCHAIN_VERSION: stable
