name: Rust - Release creation

on:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: ${{ matrix.platform.target }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - target: x86_64-pc-windows-gnu
            runs-on: windows-latest
          - target: x86_64-unknown-linux-musl
            runs-on: ubuntu-24.04
          - target: x86_64-apple-darwin
            runs-on: macOS-latest

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install cross (for Linux only)
        if: ${{ matrix.platform.target == 'x86_64-unknown-linux-musl' }}
        run: cargo install cross

      - name: Compile
        uses: houseabsolute/actions-rust-cross@v1
        with:
          target: ${{ matrix.platform.target }}
          args: "--bin adb_cli --release"
          force-use-cross: ${{ matrix.platform.target == 'x86_64-unknown-linux-musl' }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.target }}
          path: |
            target/${{ matrix.platform.target }}/release/adb_cli
            target/${{ matrix.platform.target }}/release/adb_cli.exe
