name: Rust - Release creation

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  create-release:
    name: Build ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - target: x86_64-pc-windows-gnu
            runs-on: windows-latest
          - target: x86_64-unknown-linux-musl
            runs-on: ubuntu-24.04
          - target: x86_64-apple-darwin
            runs-on: macOS-latest

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Compile
        uses: houseabsolute/actions-rust-cross@v1
        with:
          target: ${{ matrix.platform.target }}
          args: "--bin adb_cli --release"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Binaries
          path: target
