name: Rust - Release creation

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  create-release:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            x86_64-pc-windows-gnu,
            x86_64-unknown-linux-musl,
            x86_64-apple-darwin,
          ]

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Compile
        uses: houseabsolute/actions-rust-cross@v1
        with:
          target: ${{ matrix.target }}
          args: "--bin adb_cli --release"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Binaries
          path: target
