name: Rust - Release creation

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  create-release:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            x86_64-pc-windows-gnu,
            x86_64-unknown-linux-musl,
            x86_64-apple-darwin,
          ]

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get -y install libmagic-dev

      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MACOSX_DEPLOYMENT_TARGET: 10.10.0
        with:
          RUSTTARGET: ${{ matrix.target }}
          SRC_DIR: "adb_cli"
          EXTRA_COMMAND_FLAGS: "--bin adb_cli"
          TOOLCHAIN_VERSION: stable
